### ISSUE TITLE
64 but issue

### ISSUE THREAD

**Issue by herdsman-01** [OSCA-Kampala-Chapter/Linux-0.01_kernel_summerised#1]
My assembly files compile in 64 but form, how does one make them 32 bit, I use gcc as my compiler, I will fill in the details in the morning

**Comment by Phrunsys** [comment]
Sorry for the delay. If you're having a 64 bit machine. Kindly make sure you have GNU multilib installed so that your compiler automatically generates 32bit code where need be

**Comment by Phrunsys** [comment]
To compile and generate 32 bit code on a pure ia64 or x86_64. Install the GNU Multilib, for GCC😇

**Comment by Phrunsys** [comment]
And if you are interested in 32bit code on your 64bit arch. Manually invoke GCC with an -m32. As in: gcc -m32 -S "your_source_file.c"
